name: Testing matrix combinations from json
on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      matrix:
        description: matrix in json format
        required: true
        # To get a matrix that isn't a full cross-product is a bit tricky.
        # If you don't have php-versions also inside in the include or have more than one php-versions with the same other vars in the include, then it only uses the last include for that version.
        # If you try to put arrays into the include for php-versions, then the setup-php doesn't like it.
        # So it looks there's 3 options:
        # Full cross-product, no include.
        # Everything can only go inside the include, and specify each separately.
        # Can put things outside, and then use exclude to skip the drupal/civi ones you don't want.
        # ex 1: {"php-versions":["7.3","7.4"],"drupal":["~9.1.1","~9.2.2"],"civicrm":["5.40.x-dev","dev-master"]}
        # ex 2: {"include":[{"php-versions":"7.3","drupal":"~9.1.1","civicrm":"5.40.x-dev"},{"php-versions":"7.4","drupal":"~9.2.1","civicrm":"dev-master"}]}
        # ex 3: {"php-versions":["7.3","7.4"],"drupal":["~9.1.1","~9.2.2"],"civicrm":["5.40.x-dev","dev-master"],"exclude":[{"drupal":"~9.2.2","civicrm":"5.40.x-dev"}]}
        default: '{"include":[{"php-versions":"7.3","drupal":"~9.1.1","civicrm":"5.40.x-dev"},{"php-versions":"7.4","drupal":"~9.2.1","civicrm":"dev-master"}]}'
jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(github.event.inputs.matrix) }}
    name: blah
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
            php-version: ${{ matrix.php-versions }}
            extensions: dom, curl, libxml, mbstring, zip, pdo, mysql, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, :imagick
            coverage: none
            tools: composer:v2
      - name: Foo
        run: |
          echo ${{ github.event.inputs.matrix }}
          echo ${{ matrix.drupal }}
          echo ${{ matrix.civicrm }}
          php -v
