# This is just here to alert me when the patch no longer applies and I need to rebase it.
name: Create mink merge request
on:
  schedule:
    # Run daily at 23:13 GMT
    - cron: '13 23 * * *'
jobs:
  phpunit:
    runs-on: ubuntu-latest
    name: Create merge request
    steps:
      - uses: shivammathur/setup-php@v2
        with:
            php-version: 8.1
            extensions: dom, curl, libxml, mbstring, zip, pdo, mysql, pdo_mysql, bcmath, soap, intl, gd, exif, iconv
            coverage: none
            tools: composer:v2
      - name: Download civix
        run: |
          cd $GITHUB_WORKSPACE
          git clone https://github.com/totten/civix.git civix
          cd civix
          # Make it work with composer v2
          rm composer.lock
          sed -i -e 's/civicrm\/cv".*/civicrm\/cv": "dev-master",/' composer.json
          COMPOSER_MEMORY_LIMIT=-1 composer install
          # patch it
          curl -L -o mink.patch https://github.com/totten/civix/compare/master...demeritcowboy:mink.patch
          git apply mink.patch
