name: quicktest
on:
  workflow_dispatch:
    branches:
      - main   
    inputs:
      thing:
        description: Thing
        required: false
jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - foo: ${{ github.event.inputs.thing }}            
    name: quick test ${{ matrix.foo }}
    steps:
      - uses: shivammathur/setup-php@v2
        with:
            php-version: 7.4
            extensions: dom, curl, libxml, mbstring, zip, pdo, mysql, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, :imagick
            coverage: none
            tools: composer:v2
      - name: php config
        run: |
          # The `:imagick` in the extensions line above should remove it from the config.
          php -r '$x = extension_loaded("imagick"); var_dump($x);'
          php -r '$x = function_exists("imagecreatefrompng"); var_dump($x);'
      - name: xml pre-parse
        run: curl -L -O https://raw.githubusercontent.com/civicrm/civicrm-core/master/xml/version.xml
      - name: xml parse
        id: xmlparse
        uses: mavrosxristoforos/get-xml-info@1.0
        with:
          xml-file: 'version.xml'
          xpath: '//version_no'
      - name: use parsed xml
        run: |
          alphaver=${{ steps.xmlparse.outputs.info }}
          masterver=${alphaver%.alpha1}
          rcver=`awk "BEGIN {print $masterver - 0.01}"`
          echo ${rcver}.x-dev
      # It seems like there should be shorthand for this instead of 8 lines
      - name: checkstatus1
        if: ${{ success() }}
        run: |
          echo "RUNSTATUS=PASS" >> $GITHUB_ENV
      - name: checkstatus2
        if: ${{ failure() }}
        run: |
          echo "RUNSTATUS=FAIL" >> $GITHUB_ENV
      - name: finale
        run: |
          thing=${{ github.event.inputs.thing }}
          temp1=${thing%/-/merge_requests/*}
          projectname=${temp1#https://*/}
          # close enough?
          urlencoded=${projectname//\//%2F}
          domain=${temp1%/$projectname}
          mrid=${thing##*/}
          echo ${domain}/api/v4/projects/${urlencoded}/merge_requests/${mrid}/notes?body=${{ env.RUNSTATUS }}+%28CiviCarrot%29
