name: quicktest4
on:
  workflow_dispatch:
jobs:
  quickie:
    runs-on: ubuntu-latest
    name: quick test
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: dom, curl, libxml, mbstring, zip, pdo, mysql, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, :imagick
          coverage: none
          tools: composer:v2
      - name: env1
        run: |
          echo "EXITEARLY=n" >> $GITHUB_ENV
          if [ "a" != "b" ]; then
            echo "EXITEARLY=y" >> $GITHUB_ENV
          fi
      - name: env2
        if: ${{ env.EXITEARLY == 'y' }}
        run: |
            echo Exiting early
      - name: env3
        if: ${{ (success() || failure()) && (env.EXITEARLY == 'y') }}
        run: |
            echo Exited early earlier
