name: quicktest
on:
  workflow_dispatch:
    branches:
      - main   
    inputs:
      thing:
        # ${{ github.event.inputs.thing }}      
        description: Thing
        required: false
        # The value gets interpreted as a json string put between [] (so an array), and we use fromJSON below.
        # so e.g. '"7.3", "7.4"' becomes ["7.3", "7.4"]
        default: '"7.4"'
jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Setup matrix combinations
        id: setup-matrix-combinations
        run: |
          MATRIX_PARAMS_COMBINATIONS='{"php-versions": "7.3", "cver": "1"}, {"php-versions": "7.4", "cver": "2"}'
          echo ::set-output name=matrix-combinations::{\"php-versions\":[${{ github.event.inputs.thing }}],\"include\":[$MATRIX_PARAMS_COMBINATIONS]}
    outputs:
      matrix-combinations: ${{ steps.setup-matrix-combinations.outputs.matrix-combinations }}
  phpunit:
    runs-on: ubuntu-latest
    needs: setup-matrix
    strategy:
      matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix-combinations) }}        
    name: quick test ${{ github.event.inputs.thing }}
    steps:
      - uses: shivammathur/setup-php@v2
        with:
            php-version: ${{ matrix.php-versions }}
            extensions: dom, curl, libxml, mbstring, zip, pdo, mysql, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, :imagick
            coverage: none
            tools: composer:v2
      - name: if syntax
        # doesn't work:   if: ${{ "$GITHUB_REPOSITORY" == 'demeritcowboy/testCI' }}
        run: |
          if [ "$GITHUB_REPOSITORY" = "someother/testCI" ]; then
            echo "wrong repo $GITHUB_REPOSITORY"
            exit -1
          fi
      - name: use matrix vars
        env:
          CIVERT: ${{ matrix.cver }}
        run: echo $CIVERT
      - name: php config
        run: |
          # The `:imagick` in the extensions line above should remove it from the config.
          php -r '$x = extension_loaded("imagick"); var_dump($x);'
          php -r '$x = function_exists("imagecreatefrompng"); var_dump($x);'
      - name: xml pre-parse
        run: curl -L -O https://raw.githubusercontent.com/civicrm/civicrm-core/master/xml/version.xml
      - name: xml parse
        id: xmlparse
        uses: mavrosxristoforos/get-xml-info@1.0
        with:
          xml-file: 'version.xml'
          xpath: '//version_no'
      - name: use parsed xml
        run: |
          alphaver=${{ steps.xmlparse.outputs.info }}
          masterver=${alphaver%.alpha1}
          rcver=`awk "BEGIN {print $masterver - 0.01}"`
          echo ${rcver}.x-dev
      # It seems like there should be shorthand for this instead of 8 lines
      - name: checkstatus1
        if: ${{ success() }}
        run: |
          echo "RUNSTATUS=PASS" >> $GITHUB_ENV
      - name: checkstatus2
        if: ${{ failure() }}
        run: |
          echo "RUNSTATUS=FAIL" >> $GITHUB_ENV
      - name: finale
        run: |
          thing=https://lab.civicrm.org/something/else.git
          temp1=${thing%/-/merge_requests/*}
          projectname=${temp1#https://*/}
          # close enough?
          urlencoded=${projectname//\//%2F}
          domain=${temp1%/$projectname}
          mrid=${thing##*/}
          echo ${domain}/api/v4/projects/${urlencoded}/merge_requests/${mrid}/notes?body=${{ env.RUNSTATUS }}+%28CiviCarrot%29
