name: quicktest
on:
  workflow_dispatch:
    branches:
      - main   
    inputs:
      thing:
        description: Thing
        required: false
jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - foo: ${{ github.event.inputs.thing }}            
    name: quick test ${{ matrix.foo }}
    steps:
      - name: xml parse
        id: xmlparse
        uses: mavrosxristoforos/get-xml-info@1.0
        with:
          xml-file: 'https://raw.githubusercontent.com/civicrm/civicrm-core/master/xml/version.xml'
          xpath: '//version_no'
      - name: use parsed xml
        run: echo ${{ steps.xmlparse.outputs.info }}
      # It seems like there should be shorthand for this instead of 8 lines
      - name: checkstatus1
        if: ${{ success() }}
        run: |
          echo "RUNSTATUS=PASS" >> $GITHUB_ENV
      - name: checkstatus2
        if: ${{ failure() }}
        run: |
          echo "RUNSTATUS=FAIL" >> $GITHUB_ENV
      - name: finale
        run: |
          thing=${{ github.event.inputs.thing }}
          temp1=${thing%/-/merge_requests/*}
          projectname=${temp1#https://*/}
          # close enough?
          urlencoded=${projectname//\//%2F}
          domain=${temp1%/$projectname}
          mrid=${thing##*/}
          echo ${domain}/api/v4/projects/${urlencoded}/merge_requests/${mrid}/notes?body=${{ env.RUNSTATUS }}+%28CiviCarrot%29
