name: Quick Tests
on:  
  workflow_dispatch:
    branches:
      - main
jobs:
  phpunit:
    runs-on: ubuntu-latest
    name: quicktest    
    steps:
      - name: does mail work?
        id: mailwork
        run: |
          sudo apt-get update -y
          sudo apt-get install -y bsd-mailx
          echo "testing 123" | mail -s "test" demeritcowboy@hotmail.com
          
