name: Quick Tests
on:  
  workflow_dispatch:
    branches:
      - main
jobs:
  phpunit:
    runs-on: ubuntu-latest
    name: quicktest    
    steps:
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: |
          echo "${{ github.job }}"
          # job context doesn't seem to contain anything except status
          echo "$JOB_CONTEXT"
          # This is useful as https://github.com/demeritcowboy/testCI/actions/runs/XXX but is one level higher than the logs
          echo "${{ github.run_id }}"
      - name: send smtp
        uses: wadeww/send-email-action@v1
        with:
          server_address: smtp.mail.yahoo.com
          port: 465
          username: ${{secrets.MAIL_USERNAME}}
          # This is a temporary app password, not the real password
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Workflow finished
          body: Job completed ${{job.status}}
          to: clam_octagon@yahoo.ca
          from: clam_octagon@yahoo.ca
