name: quicktest
on:
  workflow_dispatch:
    branches:
      - main    
jobs:
  phpunit:
    runs-on: ubuntu-latest
    name: quick test
    steps:
      # It seems like there should be shorthand for this instead of 8 lines
      - name: checkstatus1
        if: ${{ success() }}
        run: |
          echo "RUNSTATUS=PASS" >> $GITHUB_ENV
      - name: checkstatus2
        if: ${{ failure() }}
        run: |
          echo "RUNSTATUS=FAIL" >> $GITHUB_ENV
      - name: finale
        run: |
          echo ${{ env.RUNSTATUS }}:+something/something/2
