name: Quick Tests
on:  
  workflow_dispatch:
    branches:
      - main
jobs:
  phpunit:
    runs-on: ubuntu-latest
    name: quicktest    
    steps:
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: |
          echo "$JOB_CONTEXT"
          echo "${{ github.run_id }}"
          echo "${{ github.run_number }}"
      - name: send smtp
        uses: wadeww/send-email-action@v1
        with:
          server_address: smtp.mail.yahoo.com
          port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Workflow finished
          body: Job completed ${{job.status}}
          to: clam_octagon@yahoo.ca
          from: clam_octagon@yahoo.ca
