name: Quick Tests
on:  
  workflow_dispatch:
    branches:
      - main
jobs:
  phpunit:
    runs-on: ubuntu-latest
    name: quicktest    
    steps:
      - name: send smtp
        uses: wadeww/send-email-action@v1
        with:
          server_address: smtp.mail.yahoo.com
          port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Workflow finished
          body: Job completed ${{job.status}}
          to: clam_octagon@yahoo.ca
          from: clam_octagon@yahoo.ca
