name: quicktest
on:
  workflow_dispatch:
    branches:
      - main   
    inputs:
      thing:
        description: Thing
        required: false
jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - foo: ${{ github.event.inputs.thing }}            
    name: quick test ${{ matrix.foo }}
    steps:
      # It seems like there should be shorthand for this instead of 8 lines
      - name: checkstatus1
        if: ${{ success() }}
        run: |
          echo "RUNSTATUS=PASS" >> $GITHUB_ENV
      - name: checkstatus2
        if: ${{ failure() }}
        run: |
          echo "RUNSTATUS=FAIL" >> $GITHUB_ENV
      - name: finale
        run: |
          temp1=${${{ github.event.inputs.thing }}%/-/merge_requests/*}
          projectname=${temp1#https://*/}
          # close enough?
          urlencoded=${projectname//\//%2F}
          domain=${temp1%/$projectname}
          mrid=${${{ github.event.inputs.thing }}##*/}
          echo ${domain}/api/v4/projects/${urlencoded}/merge_requests/${mrid}/notes?body=${{ env.RUNSTATUS }}+%28CiviCarrot%29
