name: quicktest
on:
  workflow_dispatch:
    branches:
      - main   
    inputs:
      prnum:
        description: PR Number
        required: false
jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - foo: ${{ github.event.inputs.prnum }}            
    name: quick test ${{ matrix.foo }}
    steps:
      # It seems like there should be shorthand for this instead of 8 lines
      - name: checkstatus1
        if: ${{ success() }}
        run: |
          echo "RUNSTATUS=PASS" >> $GITHUB_ENV
      - name: checkstatus2
        if: ${{ failure() }}
        run: |
          echo "RUNSTATUS=FAIL" >> $GITHUB_ENV
      - name: finale
        run: |
          echo ${{ env.RUNSTATUS }}:+something/something/2
