name: quicktest5
on:
  workflow_dispatch:
jobs:
  quickie:
    runs-on: ubuntu-latest
    name: quick test
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: dom, curl, libxml, mbstring, zip, pdo, mysql, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, :imagick
          coverage: none
          tools: composer:v2
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: CiviCARROT Unit tests
          from: demeritcowboy@gmail.com
          to: demeritcowboy@gmail.com
          body: Visit https://github.com/semperit/CiviCARROT/actions/runs/${{ github.run_id }} to view logs and artifacts.
