name: quicktest3
on:
  workflow_dispatch:
jobs:
  quickie:
    runs-on: ubuntu-latest
    name: quick test
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: dom, curl, libxml, mbstring, zip, pdo, mysql, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, :imagick
          coverage: none
          tools: composer:v2
      - name: is nginx here?
        run: |
          #cat /etc/nginx/nginx.conf
          #sudo systemctl start nginx 
          #curl http://127.0.0.1:80/
          #nginx -V
          #ls -lR /usr/share/nginx
          #ls -lR /etc/nginx
          #cat /etc/nginx/sites-available/default
          #sudo cp /usr/sbin/php-fpm7.4 /usr/bin/php-fpm
          #php-fpm -v
          php -S 127.0.0.1:8080 -t foo/ &
      - name: separate step to buy time
        run: |
          mkdir foo
          echo '<?php phpinfo();' > foo/index.php          
      - name: buy more time
        run: |
          curl http://127.0.0.1:8080/
