name: statistics 
on:  
  workflow_dispatch:
    branches:
      - main
    inputs:
      prnum:
        description: PR Number
        required: false
jobs:
  stats:
    runs-on: ubuntu-latest
    name: Statistics test
    steps:
      - uses: actions/checkout@v2
      - name: starttimer
        run: |
          cd $GITHUB_WORKSPACE
          date +%s > timerfile
      - name: do something
        run: |
          cd $GITHUB_WORKSPACE
          curl -L -O https://download.civicrm.org/civicrm-5.36.1-drupal.tar.gz
          ls -al
      - name: calc
        run: |
          cd $GITHUB_WORKSPACE
          STARTTIME=`cat timerfile`
          TIMEUSED=$(( `date +%s` - $STARTTIME ))
          echo $TIMEUSED
          SPACEUSED=`du -s | cut -f1`         
          echo $SPACEUSED          
        env:
          COMPOSER_MEMORY_LIMIT: -1
          SYMFONY_DEPRECATIONS_HELPER: weak
