name: test nginx+drupal
on:
  workflow_dispatch:
jobs:
  nginxdrupal:
    runs-on: ubuntu-latest
    name: see if this works
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: db
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: dom, curl, libxml, mbstring, zip, pdo, mysql, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, :imagick
          coverage: none
          tools: composer:v2
      - name: setup nginx
        run: |
          #sudo cp /usr/sbin/php-fpm7.4 /usr/bin/php-fpm          
          #cat /etc/nginx/sites-available/default
          sudo cp $GITHUB_WORKSPACE/drupal.nginx.conf /etc/nginx/sites-available/default
          # sledgehammer approach to configuring php
          sudo rm -f /etc/php/7.4/fpm/conf.d/20-xdebug.ini
          sudo rm -f /etc/php/7.4/mods-available/xdebug.ini
          sudo sed -i 's/memory_limit = 128M/memory_limit = -1/' /etc/php/7.4/fpm/php.ini
          sudo sed -i 's/max_execution_time = 30/max_execution_time = 0/' /etc/php/7.4/fpm/php.ini
          sudo sed -i 's/xdebug.mode=coverage/xdebug.mode = off/' /etc/php/7.4/fpm/php.ini
          sudo systemctl restart php7.4-fpm
          sudo systemctl start nginx
      - name: sanity check
        run: |
          mkdir ~/drupal
          mkdir ~/drupal/web
          echo '<?php phpinfo();' > ~/drupal/web/index.php
          curl http://127.0.0.1:8080/index.php
          rm -rf ~/drupal
      - name: Download Drupal
        run: |
          COMPOSER_MEMORY_LIMIT=-1 composer create-project drupal/recommended-project:~9.4.0 ~/drupal --no-interaction
          cd ~/drupal
          composer config extra.enable-patching true
          composer config extra.compile-mode all
          composer config minimum-stability dev
          composer config prefer-stable true
          composer config --no-interaction --no-plugins allow-plugins.civicrm/composer-compile-plugin true
          composer config --no-interaction --no-plugins allow-plugins.civicrm/composer-downloads-plugin true
          composer config --no-interaction --no-plugins allow-plugins.civicrm/civicrm-asset-plugin true
          composer config --no-interaction --no-plugins allow-plugins.cweagans/composer-patches true
          COMPOSER_MEMORY_LIMIT=-1 composer require drupal/core-dev-pinned:~9.4.0
          # COMPOSER_MEMORY_LIMIT=-1 composer require drush/drush
      - name: Install Drupal
        run: |
          # cd ~/drupal
          # ./vendor/drush/drush/drush -y -l http://127.0.0.1 site-install standard --db-url='mysql://root:@127.0.0.1:${{ job.services.mysql.ports[3306] }}/db' --site-name=TestDrupal --account-pass=admin
          # chmod +w web/sites/default
      - name: sanity check 2
        run: |
          # curl http://127.0.0.1:8080/
      - uses: nanasess/setup-chromedriver@master
      - name: Run chromedriver
        run: chromedriver &
      - name: compare with regular
        run: |
          sudo systemctl stop nginx
          sudo systemctl stop php7.4-fpm
          php -S 127.0.0.1:8080 -t ~/drupal/web &
      - name: Run PHPUnit
        run: |
          # mkdir $BROWSERTEST_OUTPUT_DIRECTORY
          cd ~/drupal
          vendor/bin/phpunit -c web/core web/core/tests/Drupal/FunctionalJavascriptTests/BrowserWithJavascriptTest.php
        env:
          SYMFONY_DEPRECATIONS_HELPER: 999999
          SIMPLETEST_DB: mysql://root:@127.0.0.1:${{ job.services.mysql.ports[3306] }}/db
          SIMPLETEST_BASE_URL: http://127.0.0.1:8080
          MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", {"browserName":"chrome","chromeOptions":{"args":["--disable-gpu", "--no-sandbox", "--headless"]}}, "http://127.0.0.1:9515"]'
          BROWSERTEST_OUTPUT_DIRECTORY: ''
