name: Unit Tests
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main
    inputs:
      prnum:
        description: PR Number
        required: false
jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - drupal: '^9.1'
            civicrm: '~5.41.0'
    name: Drupal ${{ matrix.drupal }} | CiviCRM ${{ matrix.civicrm }}
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: db
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
            php-version: 7.3
            extensions: dom, curl, libxml, mbstring, zip, pdo, mysql, pdo_mysql, bcmath, soap, intl, gd, exif, iconv
            coverage: none
            tools: composer:v1
      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v2
        with:
            path: ${{ steps.composercache.outputs.dir }}
            key: ${{ runner.os }}-${{ matrix.drupal }}-composer-${{ hashFiles('**/composer.json') }}
            restore-keys: ${{ runner.os }}-composer-
      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
      - name: Download cv
        run: |
          cd $GITHUB_WORKSPACE
          git clone https://github.com/civicrm/cv.git civicrm-cv
          cd civicrm-cv
          COMPOSER_MEMORY_LIMIT=-1 composer install
      - name: Download Drupal
        run: |
          COMPOSER_MEMORY_LIMIT=-1 composer create-project drupal/recommended-project:${{ matrix.drupal }} ~/drupal --no-interaction
          cd ~/drupal
          composer config extra.enable-patching true
          composer config extra.compile-mode all
          composer config minimum-stability dev          
      - name: Download CiviCRM ${{ matrix.civicrm }}
        run: |
          cd ~/drupal
          COMPOSER_MEMORY_LIMIT=-1 composer require civicrm/civicrm-asset-plugin:'~1.1' civicrm/civicrm-{core,packages,drupal-8}:${{ matrix.civicrm }} --no-suggest
          COMPOSER_MEMORY_LIMIT=-1 composer require phpunit/phpunit:'^7.5' drush/drush
      - name: Install Drupal
        run: |
          cd ~/drupal
          ./vendor/drush/drush/drush -y -l http://civi.localhost site-install standard --db-url='mysql://root:@127.0.0.1:${{ job.services.mysql.ports[3306] }}/db' --site-name=TestCivi --account-pass=admin
          chmod +w web/sites/default
      - name: Install CiviCRM
        run: |
          cd ~/drupal
          $GITHUB_WORKSPACE/civicrm-cv/bin/cv core:install --cms-base-url=http://civi.localhost -m loadGenerated=1
      # This task is silly but just doing proof of concept right now
      - name: Get some code to test
        run: |
          mkdir -p ~/drupal/web/sites/default/files/civicrm/ext
          cd ~/drupal/web/sites/default/files/civicrm/ext
          git clone https://lab.civicrm.org/extensions/cdntaxreceipts.git
      - name: Apply PR
        if: ${{ github.event.inputs.prnum != 0 }}
        run: |
          cd  ~/drupal/web/sites/default/files/civicrm/ext/cdntaxreceipts
          curl -O https://lab.civicrm.org/extensions/cdntaxreceipts/-/merge_requests/${{ github.event.inputs.prnum }}.patch
          git apply ${{ github.event.inputs.prnum }}.patch  
      - name: Run PHPUnit
        run: |
          export PATH=$PATH:$GITHUB_WORKSPACE/civicrm-cv/bin
          export CIVICRM_UF=UnitTests
          export CIVICRM_SETTINGS=~/drupal/web/sites/default/civicrm.settings.php
          cd ~/drupal/vendor/civicrm/civicrm-core
          # Sanity check to see if plain core tests run
          ../../bin/phpunit tests/phpunit/CRM/Case/BAO/CaseTest.php
          # Now run our tests
          ../../bin/phpunit ../../../web/sites/default/files/civicrm/ext/cdntaxreceipts/tests/phpunit/CRM/Cdntaxreceipts/HookTest.php
          ../../bin/phpunit ../../../web/sites/default/files/civicrm/ext/cdntaxreceipts/tests/phpunit/CRM/Cdntaxreceipts/UtfTest.php
        env:
          COMPOSER_MEMORY_LIMIT: -1
          SYMFONY_DEPRECATIONS_HELPER: weak
